### ISSUE TITLE
Broken Fork Repo Link 

### ISSUE THREAD

**Issue by alt113** [gallettilance/CS506-Fall2020#6]
When we reach [Workflow 2: Submit Pull Request, Steps A to Z ](https://github.com/gallettilance/CS506-Fall2020/blob/master/00-git/exercises/exercise2.md#workflow-2--submit-pull-request-steps-a-to-z), the first step is to fork the repository but it is still set to the Spring 2020 repo which no longer exists.

Its a simple fix and I get what to change but when you blindly click the repo link at first its a little surprising to be met with en Error 404.

**Comment by gallettilance** [comment]
Thanks for catching that! I've created #10 to address this. Please review when you get a chance
